# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peptide',
            fields=[
                ('pdb_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_amp', models.BooleanField()),
                ('hfobic_area', models.CharField(max_length=96)),
                ('hfobic_avg', models.FloatField()),
                ('hdl', models.IntegerField()),
                ('beta_hdl', models.IntegerField()),
                ('alpha_hdl', models.IntegerField()),
                ('alpha_beta', models.IntegerField()),
                ('alpha_beta_hdl', models.IntegerField()),
                ('charge', models.FloatField()),
                ('m_dipol', models.FloatField()),
                ('charge_amt_atm', models.FloatField()),
                ('m_dipol_amt_atm', models.FloatField()),
                ('sequence', models.TextField()),
            ],
        ),
    ]
