# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbAMPdatabase', '0002_auto_20160922_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='peptide',
            name='organizm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
