# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbAMPdatabase', '0003_peptide_organizm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peptide',
            old_name='alpha_beta',
            new_name='alpha_Helix_beta_sheet',
        ),
        migrations.RenameField(
            model_name='peptide',
            old_name='alpha_beta_hdl',
            new_name='alpha_Helix_beta_sheet_hairpin',
        ),
        migrations.RenameField(
            model_name='peptide',
            old_name='alpha_hdl',
            new_name='alpha_helix',
        ),
        migrations.RenameField(
            model_name='peptide',
            old_name='beta_hdl',
            new_name='beta_sheet',
        ),
        migrations.RenameField(
            model_name='peptide',
            old_name='hdl',
            new_name='hairpin',
        ),
        migrations.RenameField(
            model_name='peptide',
            old_name='organizm',
            new_name='organism',
        ),
        migrations.AlterField(
            model_name='peptide',
            name='sequence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
