# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbAMPdatabase', '0004_auto_20161104_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peptide',
            old_name='alpha_Helix_beta_sheet',
            new_name='alpha_helix_beta_sheet',
        ),
        migrations.RenameField(
            model_name='peptide',
            old_name='alpha_Helix_beta_sheet_hairpin',
            new_name='alpha_helix_beta_sheet_hairpin',
        ),
    ]
