# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbAMPdatabase', '0005_auto_20161104_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='peptide',
        ),
    ]
