# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbquery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMP',
        ),
        migrations.DeleteModel(
            name='Non_AMP',
        ),
    ]
