# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbquery', '0002_auto_20160801_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMP',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hfobic_area', models.CharField(max_length=96)),
                ('hfobic_avg', models.FloatField()),
                ('hdl', models.IntegerField()),
                ('beta_hdl', models.IntegerField()),
                ('alpha_hdl', models.IntegerField()),
                ('alpha_beta', models.IntegerField()),
                ('alpha_beta_hdl', models.IntegerField()),
                ('charge', models.FloatField()),
                ('m_dipol', models.FloatField()),
                ('charge_amt_atm', models.FloatField()),
                ('m_dipol_amt_atm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Non_AMP',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hfobic_area', models.CharField(max_length=96)),
                ('hfobic_avg', models.FloatField()),
                ('hdl', models.IntegerField()),
                ('beta_hdl', models.IntegerField()),
                ('alpha_hdl', models.IntegerField()),
                ('alpha_beta', models.IntegerField()),
                ('alpha_beta_hdl', models.IntegerField()),
                ('charge', models.FloatField()),
                ('m_dipol', models.FloatField()),
                ('charge_amt_atm', models.FloatField()),
                ('m_dipol_amt_atm', models.FloatField()),
            ],
        ),
    ]
