# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbquery', '0003_amp_non_amp'),
    ]

    operations = [
        migrations.AddField(
            model_name='amp',
            name='name',
            field=models.CharField(default='ampName', max_length=256),
        ),
        migrations.AddField(
            model_name='non_amp',
            name='name',
            field=models.CharField(default='ampName', max_length=256),
        ),
    ]
